### ISSUE TITLE
Expand scientific notation

### ISSUE THREAD

**Issue by nblackburn** [parsify-dev/desktop#11]
It would be better to show numbers in their full form rather than in scientic notiation reducing cognitive load.

```
3.952e+5 // 395200
```

**Comment by xxczaki** [comment]
In `1.1.0`, the scientific notation will only be used for very large numbers ;)

**Comment by Loewe1000** [comment]
Would be nice if it is used for very small numbers too. ;)
I don't want to calculate this at my own.
<img width="816" alt="image" src="https://user-images.githubusercontent.com/1015274/201315285-3a5a05c1-4ea9-45b3-88d7-a12b2b39bd3d.png">
