### ISSUE TITLE
File: Display of Filename and -path, Create New

### ISSUE THREAD

**Issue by LarsJandel** [parsify-dev/desktop#12]
First of all, thanks for the `v1.1.0` update! 🎉

Just tried the `File` options, saving and opening files work great. 👍
What came to my attention, I don't know, which file is currently open, which also means, I don't know which file will be overwritten when saving.
It would be nice to have the **filename and -path** being displayed. Of course without taking additional / too much space from the UI in the best case. Would it be possible to have it like in Visual Studio Code, being displayed next to the menu items? Or as a footer maybe. Of course, some people would like the UI to stay as minimalistic as possible, so maybe the file display could be optional and/or if using a footer, just being displayed on mouseover. [Might need some truncation when displaying the file path as well and having a small window I guess.]
Currently, there is no `New File` option. So, in case I was working on a saved file and I want to start a new one, I can simply delete the content of course, but doing a standard `Save` by accident would overwrite the previously used file. So a `New File` option would avoid this to happen and could also check and ask users if they want to save the currently open file first prior to creating a blank new _Parsify_ window with no file connection.

Thanks!

**Comment by xxczaki** [comment]
Added in `v1.1.1` ;)
