### ISSUE TITLE
Result column doesn't adapt to line breaks of expressions

### ISSUE THREAD

**Issue by LarsJandel** [parsify-dev/desktop#13]
If an expression exceeds a single line resulting in a line break, unfortunately the results of following expressions don't move down to match their expressions to the left.
Also vice versa if a result needs line breaks, see blow. I guess `time` is broken though..?
`Parsify v1.1.0 - Windows 10`

![Parsify Desktop - 1 - no line break](https://user-images.githubusercontent.com/32457827/83970196-aef44a80-a8d4-11ea-9aeb-b6547b2a6ca6.png)
![Parsify Desktop - 2 - with line break](https://user-images.githubusercontent.com/32457827/83970197-af8ce100-a8d4-11ea-9dc4-e2e015c556b8.png)

vice versa → result using line breaks:
![Parsify Desktop - 3 - line break in result](https://user-images.githubusercontent.com/32457827/83972366-0d72f600-a8e0-11ea-98b7-8ba799683f91.png)

**Comment by xxczaki** [comment]
> If an expression exceeds a single line resulting in a line break, unfortunately the results of following expressions don't move down to match their expressions to the left.

This happens as it is impossible for me to "detect" the automatic text wrapping. I could disable wrapping words completely, but then it would require adding a horizontal scroll bar, which looks pretty bad design-wise. So I'm not yet sure what approach I should take on this one. For now, resizing the window is the only option.

> I guess time is broken though..?

Yup, this is connected with #15. I would like to focus on that in the next release.

**Comment by LarsJandel** [comment]
Ah okay, I should be able to expand the window if needed - trying not to be lazy. 😉

**Comment by xxczaki** [comment]
Update: `time` and `now` commands should work correctly in the upcoming `1.2.0` release. It should be available to download in a few hours. Due to major changes in how user preferences are being stored, a manual installation will be highly recommended.

Full changelog will be available here: https://headwayapp.co/parsify-changelog

**Comment by xxczaki** [comment]
In terms of the text wrapping - I'm working on adding https://github.com/parsify-dev/desktop/issues/10, so you might no longer need to resize the window :smile:

**Comment by xxczaki** [comment]
#10 is now available in `1.2.2` :smile:

**Comment by ecciv** [comment]
A scroll bar that is automatically hidden until hovered over would be one way to solve the problem without visual clutter.

Also, I have a different word wrap problem.

![image](https://user-images.githubusercontent.com/70523470/91724787-1c470d00-eb9e-11ea-85c7-94622716c292.png)

Word wrap cuts it at the right edge of the entire window, not at where the results pane starts. Thus there will be words hidden behind the results pane, which makes word wrap useless. Probably a bug introduced when #10 was implemented.
