### ISSUE TITLE
colon symbol [ : ] breaks headers and comments

### ISSUE THREAD

**Issue by LarsJandel** [parsify-dev/desktop#14]
This just came to my attention as I had a colon symbol in a header.
Hm okay, looking at the manual, you incorporated labels, which are followed by a colon...
I guess, for headers and line comments, you could check for the `#` or `//` at the beginning of the line. For inline comments..? 🤷‍♂️ ...checking, if a colon symbol is preceded by `//` anywhere to the left could work to disable the `:` as a label token within inline comments as well.
Thanks.
[Parsify v1.1.0 - Windows 10]

![Parsify Desktop - colon symbol breaks comments](https://user-images.githubusercontent.com/32457827/83980118-6d36c480-a913-11ea-8e60-e28f11005a3e.png)

**Comment by xxczaki** [comment]
Fixed in `v1.1.1` ;)
