### ISSUE TITLE
Time as variable - currently gets locked during a session

### ISSUE THREAD

**Issue by LarsJandel** [parsify-dev/desktop#15]
I am actually not sure if this is a bug or an intended behavior:
When I am getting a time e.g. `time in Berlin` | `11:49 CEST`, this will turn `time in Berlin` into a fixed variable, meaning it won't update to the current time: Writing the same expression, results in the previously set / old time. I guess, this could make sense when using it in an expression, which shouldn't change every minute. Currently, I have to quit and start _Parsify_ again in order to get an updated time.
So as said, the fixed variable might have its advantages, but could there be an option to _update_ the time variable without restarting the app? (This behavior might be true to `date` as well..?)

Thanks
[Parsify v1.1.0 - Windows 10]

**Comment by xxczaki** [comment]
Yeah, it currently doesn't update this due to memorization. Parsify Desktop uses a third-party service for time zone conversion. This is likely to change soon ;)

**Comment by xxczaki** [comment]
The new "Force recalculation" button in v1.8.0 allows to refresh the answers without reloading/restarting the app 😀

**Comment by LarsJandel** [comment]
Thanks!
