### ISSUE TITLE
SSL Error on docs.parsify.app

### ISSUE THREAD

**Issue by ianfabs** [parsify-dev/desktop#18]
# Issue

When trying to visit https://docs.parsify.app/ I receive an SSL Certificate error. It seems as though it is configured for `*.gitbooks.io`

## Example
![SSL Error in Firefox on Arch Linux](https://samples-06042020.s3-us-west-2.amazonaws.com/Parsify_SSL_ERROR_BAD_CERT_DOMAIN-06-10-2020.png)

## Env
OS: Arch Linux
Browser: Firefox

**Comment by xxczaki** [comment]
Update: I wasn't able to reproduce this issue on Firefox 77 (running in the cloud, on macOS Mojave):

![0002screenshot](https://user-images.githubusercontent.com/22645979/84546609-fda14a80-ad01-11ea-8700-3131a1ac1e0c.png)

**Comment by ianfabs** [comment]
When I visit https://xxczaki.gitbook.io/parsify it redirects me to https://docs.parsify.app/.

It works on my windows machine now, but still not on my linux box. It's probably a configuration error on my end. I can live with it working on only one machine! Thank you for your time looking into the matter, I greatly appreciate it 😀
