### ISSUE TITLE
How does Parsify handle currency updates?

### ISSUE THREAD

**Issue by LarsJandel** [parsify-dev/desktop#2]
Just wondering, how often and using which source, the currency rates are getting updated?
While being here, the ISO currency abbreviations work fine, but are you planning to integrate currency symbols as well? Like $ for US dollars, € for Euro...
Thanks.
[Yep, former Numi user, but switched to Windows. 😉]

**Comment by xxczaki** [comment]
Parsify Desktop uses [Exchange Rates API](https://exchangeratesapi.io/), which uses the exchange rates published by the [European Central Bank](https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html).

> The reference rates are usually updated around 16:00 CET on every working day, except on TARGET closing days.

I will try to add symbols for some currencies in the next update :smile:

**Comment by xxczaki** [comment]
I was also thinking about allowing users to choose different data sources for currencies.

**Comment by LarsJandel** [comment]
Cool - thanks!
