### ISSUE TITLE
Rounding errors in trig functions

### ISSUE THREAD

**Issue by flamewave000** [parsify-dev/desktop#23]
I'm getting a rounding error with basic trig functions:
`sin(pi) = 0.0000000000000001225` <- Should be 0
`sin(2*pi) = -0.0000000000000001225` <- Should be 0
`cos(pi/2) = 0.00000000000000006123` <- Should be 0

**Comment by xxczaki** [comment]
See https://github.com/josdejong/mathjs/issues/133
