### ISSUE TITLE
copying input and output simulatenously

### ISSUE THREAD

**Issue by ecciv** [parsify-dev/desktop#25]
Hi!

I'm interested in a solution to a use case where one would copy both the input and the output as text, in order to show the work behind calculations. Currently, it's easy to do in e.g. Calca, as the results are shown on the same line as the input. The same is not true in parsify, because the results are in a separate pane. 

It's not the same functionality as #22, but both are related to copying expressions and results. I just wish to copy them together, perhaps for every line in the whole document at one time.

**Comment by xxczaki** [comment]
In version `1.5.0` you can copy either just the result (by clicking the result once) or the full line using double-click. There is currently no way to do it via a keyboard shortcut, but you can follow the discussion in #22 in case you are interested 😄
