### ISSUE TITLE
Logical operators

### ISSUE THREAD

**Issue by ecciv** [parsify-dev/desktop#26]
Heya!

If, else, or, and, =!, > and < are useful for basic noncontinuous functions. In my case, this is the math I'm trying to program.

![image](https://user-images.githubusercontent.com/70523470/91861935-a611db80-ec6d-11ea-940e-8a65b04c582b.png)

BR
Victor

**Comment by xxczaki** [comment]
[Here](https://mathjs.org/docs/expressions/syntax.html#operators) you can find a table with the currently supported operators (including the logical ones). Could you please let me know what new operators would you like to see in Parsify? 

I'm not sure if I'm correct, but according to the picture, you would like the `for` operator, right?

**Comment by xxczaki** [comment]
Closed due to inactivity.
