### ISSUE TITLE
Output error messages

### ISSUE THREAD

**Issue by ecciv** [parsify-dev/desktop#27]
Hi!

I was struggling a bit with a calculation, and after a while I figured out that it didn't give me an answer because there was an error with the units. 

![image](https://user-images.githubusercontent.com/70523470/91864688-cdb67300-ec70-11ea-9d32-062ee752afe6.png)

Obviously, the result of n(h) in this case contains both metres and a unitless value, which is an unacceptable answer. An error output would be useful for weeding out math errors such as this. Initially I thought n(h) simply wasn't finding h as a variable.

**Comment by ecciv** [comment]
![image](https://user-images.githubusercontent.com/70523470/91865939-394d1000-ec72-11ea-85b2-d4cd8e57949b.png)

Also, it would be useful if the row in which i input the formula would output the result, instead of repeating the formula name. As you can see, calling the variable n(h) a second time does output the result.

**Comment by xxczaki** [comment]
You can now add the `DEBUG=true` flag in Settings -> Plugins -> Configuration to output math errors.
