### ISSUE TITLE
Parsify doesn't forget a variable value if that variable is also the name of a unit

### ISSUE THREAD

**Issue by ecciv** [parsify-dev/desktop#28]
1. I write code where m is the unit metres, and everything is going well
2. I accidentally name a variable m, and everything changes
3. I rename my variable to mc, to indicate that it's the constant m, not the unit m. 
4. Everything doesn't change back to m being just a unit.

It seems parsify is remembering my mistake here! That's not what I wish would happen.

![image](https://user-images.githubusercontent.com/70523470/91866768-25ee7480-ec73-11ea-8fca-ef40c79b952c.png)

(the output value of w=80 m is obviously incorrect, m has no numerical value in the code any longer.)

**Comment by ecciv** [comment]
I wasn't able to reset m to being a unit, so I was forced to create a new document or remove the units from my calculation.

**Comment by xxczaki** [comment]
Looks like a bug, thanks for catching that! The currently recommended workaround is to restart the app or, as you said - create a new document.

**Comment by ecciv** [comment]
![image](https://user-images.githubusercontent.com/70523470/92367377-9fb0b300-f0f6-11ea-981c-a580add3ea12.png)

I had a similar issue where Parsify seems to have remembered the value of e from the previous document I had open. As you can see, I have not defined e anywhere, but it says it's 0.2. What it was supposed to be is eulers number. What I think I did was i simply was writing one document, then i saved that and opened an older document in the same instance of parsify. This one really threw me off guard!

**Comment by xxczaki** [comment]
In 1.3.0 you can refresh the parser context using the context menu (right-click). Furthermore, the parser variables are reset when creating a new file or moving to an existing one.
