### ISSUE TITLE
Can't get calculations working

### ISSUE THREAD

**Issue by chilikasha** [parsify-dev/desktop#3]
Hi,

I pasted some calculations from Numi (similar app to yours) and can't get it working.
```
price = 150

# excise
markUpRate = 75
exciseTax = 10
eTax = price * (1 + markUpRate / 100) * exciseTax / 100
```

<img width="736" alt="Screen Shot 2020-06-04 at 11 18 08" src="https://user-images.githubusercontent.com/3147449/83732699-19975300-a655-11ea-9053-67d068ba0be3.png">

Tried with `times`, `divided by` - same result.
What am I doing wrong.
Wanted to check docs, but the page doesn't open

Thanks

**Comment by LarsJandel** [comment]
You are running the demo, which only processes three lines. So your final fourth line doesn't get calculated.

**Comment by chilikasha** [comment]
ok, thanks.
but how should I know this
> you can also purchase a lifetime license, which activates some exciting additional features, like custom units and plugins. It also supports further development!

**Comment by LarsJandel** [comment]
Just checking again, where I read that. Funny enough, here it say 5 lines:
https://docs.parsify.app/miscellaneous/free-vs-activated
Maybe the author comments on that as well. I am just testing it myself atm. 😉

**Comment by xxczaki** [comment]
Only the first 5 lines are evaluated without activation (this includes the "blank" lines as well).
