### ISSUE TITLE
Issue when app startup at Ubuntu 20.10

### ISSUE THREAD

**Issue by joaovicentefs** [parsify-dev/desktop#33]
Hi mate @xxczaki i'm prouded  user of Parsify. 
After update from 1.2.2 to the 1.4.1 version i allways receive a similar message when startup the app. This is the message:

> Unhandled Promise Rejection
> TypeError: Cannot read property 'value' of undefined
>     at IpcMainImpl.<anonymous> (/opt/Parsify Desktop/resources/app.asar/app/background.js:1:11092)

Do you know how can i hanndle with this? As an workaround i'm did an downgrade to 1.2.2 version
To give you more information my OS is Ubuntu 20.10

_Originally posted by @joaovicentefs in https://github.com/parsify-dev/desktop/issues/32#issuecomment-749885166_

**Comment by xxczaki** [comment]
Hi,

Sorry for a late reply, but I was busy with the latest release. I just published version 1.5.0 of Parsify Desktop, which fixed this issue completely. Please download it from https://download.parsify.app and let me know if you will encounter any additional issues.

Best,

Antoni Kępiński

> a@kepinski.me // xxczaki@pm.me

> [https://kepinski.me](https://kepinski.me/)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
