### ISSUE TITLE
v1.5.1 - Windows installer broken?

### ISSUE THREAD

**Issue by LarsJandel** [parsify-dev/desktop#34]
As I wiped my laptop recently, I tried to install the latest version `v1.5.1` via `Parsify-Desktop-Setup-1.5.1.exe`. But it seems, the installation doesn't finish as all I get is the `Uninstall Parsify Desktop.exe` within `C:\Users\user\AppData\Local\Programs\parsify-desktop`, followed by the alert regarding the desktop shortcut, that Windows can't find the app exe. 🤷‍♂️

Thanks.

**Comment by ecciv** [comment]
same problem here using the installer for windows exe

**Comment by xxczaki** [comment]
@LarsJandel @ecciv 

Release `1.5.2` is now available. I tested it on 2 different Windows machines and everything worked as expected. Please let me know whether it works for you as well - if now, further investigation will be required.

**Comment by LarsJandel** [comment]
`Parsify.Desktop.Setup.1.5.2.exe` **works** again! 🎉
Thanks for the fix and a fantastic 2021.
