### ISSUE TITLE
Reload can cause hang in  Windows 10, App v1.5.2

### ISSUE THREAD

**Issue by ms3056** [parsify-dev/desktop#35]
I have the following text file. Once the data was stale (after  few minutes) I tried View>Reload and the app seemed to crash. No errors, just a hang, no text displayed in the app just a blank background. 

It also seems to need you to click "enter" from a restart to get the parsing going. What is the refresh rate - is it 100% manual, and is "reload" the correct function? 

Before reload:
![before_reload](https://user-images.githubusercontent.com/23712700/103394849-402b5700-4b6e-11eb-9e8b-22b9ebc4a968.png)

After reload:
![after_reload](https://user-images.githubusercontent.com/23712700/103394851-46b9ce80-4b6e-11eb-9d31-ce956214339f.png)

**Comment by xxczaki** [comment]
Thanks for the report, I was able to reproduce this issue under certain circumstances.

**Comment by xxczaki** [comment]
The user is no longer able to reload the app in 1.8.0.
