### ISSUE TITLE
v1.5.2: When starting the app, results of the last session do not get calculated automatically

### ISSUE THREAD

**Issue by LarsJandel** [parsify-dev/desktop#36]
as already mentioned in #35
When I close _Parsify_ with some calculations and start the app again, the result column is empty. It needs some action, some change on the left, to get the results back. I guess, the calculation routine is missing on start up..?

Thanks! [Windows 10]

**Comment by xxczaki** [comment]
I managed to reproduce this issue, but only when time calculation was used (for example `time in New York` or `PST time`). Without the following, everything was calculated instantly, without having to perform any actions.

I will continue testing and try to find a solution for the time calculation issues.

**Comment by xxczaki** [comment]
This should not longer appear in Parsify >=1.6.0
