### ISSUE TITLE
Settings are not getting saved

### ISSUE THREAD

**Issue by LarsJandel** [parsify-dev/desktop#38]
v1.5.2 | Windows 10
I tried first changing the _Date format_, also tried enabling _Always on top_. It seems, changes within the _Settings_ do not get saved: They get discarded when clicking the `x` in order to close the _Settings_.
Thanks

**Comment by xxczaki** [comment]
Could you please check whether this behavior still exists in the recent release?

**Comment by LarsJandel** [comment]
Just checked, works fine now - thanks!
