### ISSUE TITLE
Importing Soulver 2 Files

### ISSUE THREAD

**Issue by bradbajuz** [parsify-dev/desktop#39]
I'm looking to move from Soulver 2 to Parsify. Is there a Parsify plug-in that can import or covert Soulver 2 files to Parsify?

**Comment by xxczaki** [comment]
Not yet, but I'm happy to add it if you send me an example Soulver 2 file 😄

**Comment by bradbajuz** [comment]
I do have some files that I could provide you. Soulver 2 files are just XML files. Not sure if there is a demand to be able to read or convert Soulver 2 files over to Parsify. Soulver 2 does allow for exporting out to other formats (CSV, PDF, etc.), there are other options to get the data out of Soulver 2.

One thing Soulver does is that line numbers are variables and can be referenced.

For example:

Line1: 2+2=4
Line2: line1+2=6

This is referenced throughout a Soulver file if line numbers were used as variables.

**Comment by xxczaki** [comment]
Ok, thanks for the details. It would be great if you could send me an example Soulver 2 file with line references. I'm working on adding migration support for Soulver 2 & 3 and Numi files :smile:

**Comment by bradbajuz** [comment]
I'll put together some files for you and put them on github

**Comment by bradbajuz** [comment]
Here are a bunch of Soulver 2 files: https://github.com/bradbajuz/soulver2-files

**Comment by xxczaki** [comment]
It's been some time! However, I finally began working on supporting files from alternative applications. Currently, I have a partial-support for Soulver 2 files and full support for Numi. Everything lies in this repo:

https://github.com/parsify-dev/converter

I mentioned you in the acknowledgments section - these example files really help test the edge cases :smile: Will let you know here once the support has landed.

**Comment by xxczaki** [comment]
@bradbajuz The newly released [version 1.9.0](https://github.com/parsify-dev/desktop/releases/tag/v1.9.0) allows opening Soulver 2 and Numi files (with conversion to .txt). The whole thing should be consider an early beta due to many conversion issues, especially with Soulver 2 files. However, even when the conversion doesn't produce a perfect, compatible output, it still helps as you can manually fix invalid expressions.

**Comment by xxczaki** [comment]
I will work on improving the reliability of the converter and adding support for Soulver 3 files in the upcoming months.

**Comment by bradbajuz** [comment]
Great! I'll test it out. Thanks for all your work on implementing this.

**Comment by xxczaki** [comment]
@bradbajuz Small update, the recent release has greatly improved the reliability of the conversion for Soulver 2 files 😄  When it comes to supporting Soulver 3 files, I'm afraid it will have to wait for a bit more - after initial investigation I was unable to work out how they save line references in their files. Hopefully I will figure something out.
