### ISSUE TITLE
Don't count non-processable lines

### ISSUE THREAD

**Issue by nblackburn** [parsify-dev/desktop#4]
There is a 5 line limit but lines that are empty or just contain comments shouldn't be counted.

**Comment by nblackburn** [comment]
Related #3

**Comment by xxczaki** [comment]
I need to think about it more, but I feel like yes - they shouldn't be counted.

**Comment by xxczaki** [comment]
Works as intended.

**Comment by nblackburn** [comment]
> I need to think about it more, but I feel like yes - they shouldn't be counted.

I mean fair enough but that was quite the 180 🤔

**Comment by xxczaki** [comment]
I am willing to change this behavior in the future, but before doing so I would like to know how it works in similar applications, for example Numi.
