### ISSUE TITLE
Can't make a variable out of other variables

### ISSUE THREAD

**Issue by ekfuhrmann** [parsify-dev/desktop#40]
It looks like you can't create a variable comprised of other variables.

![image](https://user-images.githubusercontent.com/8878152/107423280-21639d00-6aea-11eb-98be-ced3c1b97aed.png)

**Comment by xxczaki** [comment]
I wasn't able to reproduce this issue. Do you own a license? If not, you may be hitting the [5 line limit in the free version](https://docs.parsify.app/miscellaneous/free-vs-activated).

**Comment by ekfuhrmann** [comment]
Oh, that most definitely is the problem. I totally missed the 5 line limit.

Thanks.
