### ISSUE TITLE
Parsify.app URL no longer has content

### ISSUE THREAD

**Issue by Gitoffthelawn** [parsify-dev/desktop#43]
This project refers the user to `parsify.app`, but that site no longer exists.

**Comment by xxczaki** [comment]
Sorry for this inconvenience, I informed about it on Twitter a few days ago. Long story short, I have some issues with the domain registrar and their support is quite bad, to say the least. Nevertheless, you can access the backup site at:

https://parsify.vercel.app/

The documentation backup is available at:

https://xxczaki.gitbook.io/parsify/

When it comes to activating your license, please download version 1.6.3 from https://github.com/parsify-dev/desktop/releases.

**Comment by Gitoffthelawn** [comment]
Thanks! I'm glad to see the project is still alive.  I just found it, and I'm interested in learning more about it.

Yes, domain registrars can be horrible.  Personally, I had such bad experiences with GoDaddy that I will never use them or recommend them.  They actually lost my domain name and claimed that I authorized the transfer.  Horrible company.
