### ISSUE TITLE
Pretty math symbols moves cursor to end of file upon replacement

### ISSUE THREAD

**Issue by working-name** [parsify-dev/desktop#44]
OS: Fedora 34
Version: AppImage, v1.6.3

If I turn on the experimental feature the cursor will move to the end of the file - I'm assuming it's a search/replace thing? codemirror?

**Comment by xxczaki** [comment]
The pretty math symbols option was removed in v1.8.0 due to various issues, including this one. I hope to re-add it in the future, rethinking the implementation first. Thank you!
