### ISSUE TITLE
Support for Multi-byte character in variable names

### ISSUE THREAD

**Issue by mekkoo** [parsify-dev/desktop#45]
Hello! Konnichiwa(こんにちは)! I'm using this product everyday in Japan.
I like this product very much. But I have only one complaint.

Sadly, this product cannot use multibyte characters in variable names.
This problem is an inconvenience for people who use Japanese, Chinese, Korean, etc.

If resolved, I will purchase a paid license.
Additionally, probably that's not just me! 😀

(Environment: Windows 10 Pro 64 bit Build 19043)

![image](https://user-images.githubusercontent.com/282262/122630943-823b5b80-d102-11eb-8923-3e892b5a506d.png)

**Comment by xxczaki** [comment]
Thanks for the suggestion and sorry that you had to wait this long. The support will land in the next release (ETA: mid/end of August).

**Comment by xxczaki** [comment]
Added in 1.8.0 - available now. Thanks!

**Comment by mekkoo** [comment]
Thank you for your support. However, even if I run it in my environment, the result is the same as before.
I'm using v1.9.2.
![image](https://user-images.githubusercontent.com/282262/153826238-e002c093-7998-4f86-9fd1-c145824f48b5.png)

**Comment by xxczaki** [comment]
Sorry for the issue, there was a bug on our side - it should be fixed in v1.9.3
