### ISSUE TITLE
Timezone not showing proper time calculation

### ISSUE THREAD

**Issue by sgeraldes** [parsify-dev/desktop#46]
Hi! 

Timezone calculation seems incorrect. I'm on UTC-03:00 and my computer is synced with a timeserver as such. 

If I type "Time in Germany" the result is UTC-2 (one hour more than my local time), where it should be UTC+02:00.

All locations I try seem to be calculated based on UTC+1 instead of the local timezone.

![image](https://user-images.githubusercontent.com/14790771/122660998-5baa0e80-d15c-11eb-80b4-bcf1796cca5b.png)

The screenshot was taken at 0:12 AM in UTC-3 / GMT-3 / Argentina Time

**Comment by xxczaki** [comment]
Fixed in 1.7.0
