### ISSUE TITLE
decimal separator: option to use a comma instead

### ISSUE THREAD

**Issue by LarsJandel** [parsify-dev/desktop#47]
Please add global settings regarding the decimal separator to switch between using a dot or comma.
So instead of e.g. used in the US:
`4,760.34`
having the usage swapped for e.g. Europe:
`4.760,34`

It would be great, is the user could change this manually, but globally for _Parsify_.

Thanks!

As reference regarding the global usage:
→ https://en.wikipedia.org/wiki/Decimal_separator#Usage_worldwide
![Decimal_separator](https://user-images.githubusercontent.com/32457827/124271503-d3554180-db3d-11eb-977b-3f509ce55d22.png)

**Comment by xxczaki** [comment]
In 1.7.0 (just released!) the decimal separator is based on the operating system's locale 😃 I may add a setting in the future.

**Comment by LarsJandel** [comment]
Thanks!
...but this doesn't work for me because of my hybrid settings. The Windows calculator uses the comma though. 🤷‍♂️😅
I am using a German QWERTZ keyboard layout with a comma on the numpad. So a setting could fix this. Thanks. 😉

![image](https://user-images.githubusercontent.com/32457827/125184865-69b1f300-e221-11eb-8309-f3f2a7ffa2d8.png)
