### ISSUE TITLE
Hi, I need help with installing a plugin I just created

### ISSUE THREAD

**Issue by carlos-contreras** [parsify-dev/desktop#48]
The plugin is already published to npm, but I don't know how to add it to my Parsify App https://www.npmjs.com/package/parsify-thousand-separator, I tried the search functionality on the app but it can't find the plugin, maybe the fact I use Linux as my main workstation OS has something to do with it?

Thanks for the help, If anything comes out from this I can help improve the docs to help others publishing and using their plugins

**Comment by xxczaki** [comment]
Hi, sorry for a late reply! This is an internal issue which will be fixed in the next release. The estimated time of release is the middle or the end of August.

**Comment by xxczaki** [comment]
Fixed in 1.8.0 - available now. Thanks!

**Comment by JonasDoesThings** [comment]
Hey @xxczaki, I've also released a plugin 2 days ago (https://github.com/k4ds3/parsify-stocks | https://www.npmjs.com/package/parsify-stocks) but it hasn't shown up in the Plugin Manager yet, and I don't see a way to manually install local plugins. Is there anything I need to do? Do I need to wait for the next release? Some clarification would be appreciated, cheers!
