### ISSUE TITLE
Expression with multiple values using a comma for decimal separator shows no result

### ISSUE THREAD

**Issue by vauhochzett** [parsify-dev/desktop#49]
I appreciate the support for the comma as a decimal separator. Sadly, I may apparently only use it exactly once in each line.

Example:
```
4.5 + 7.5 * 10          | 79.5
4,5 + 7,5 * 10          | 
4,5 + 7.5 * 10          | 79.5
4.5 + 7,5 * 10          | 79.5

1.2 + 2.3 + 3.4         | 6.9
1,2 + 2,3 + 3,4         | 
```

What I can see is that no result is displayed if more than one comma is used (see above). Very confusing!

**Comment by xxczaki** [comment]
Fixed in 1.8.0 - available now. Thanks!
