### ISSUE TITLE
Calculations not working on Linux KDE Plasma 5.22

### ISSUE THREAD

**Issue by obstrom** [parsify-dev/desktop#50]
Calculations and expressions never get resolved in the right-hand panel of the app. A grey bar appears and pulses, as if the app is attempting to load the result of the given expression, but it never gets resolved.

I'm a first time user hoping to test this app out. I'm using KDE Linux desktop. Downloaded the `parsify-desktop_1.7.0_amd64.deb` package from the Github release page. Installed using `dpkg` without any issues.

[Screenshot of app with the issue](https://www.dropbox.com/s/dqs86wbqwog8zbk/parsify_error.jpg?dl=0)

When starting the app via the terminal (`/usr/bin/parsify-desktop`) I get this console output:
```
Electron's autoUpdater does not support the 'linux' platform
(node:59656) UnhandledPromiseRejectionWarning: Error: The name org.freedesktop.secrets was not provided by any .service files
(Use `parsify-desktop --trace-warnings ...` to show where the warning was created)
(node:59656) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:59656) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error occurred in handler for 'eval-expressions': [Error: The name org.freedesktop.secrets was not provided by any .service files]
```

- **Parsify-desktop:** 1.7.0
- **OS:** Linux KDE neon 5.22 (Ubuntu-based)
- **Linux kernel:** 5.11.0-34
- **KDE Plasma:** 5.22.5
- **Graphics platform**: X11

**Comment by xxczaki** [comment]
Thanks for reporting this. Could you please uninstall the existing version from your computer and instead install the most recent release, that is, v1.8.0? Let me know if the problem still exists there.

**Comment by obstrom** [comment]
Thanks for getting back to me!

Sorry, I still have the same issue with v1.8.0

I uninstalled the previous version using `dpkg --purge parsify-desktop`, then installed the new one with `dpkg -i parsify-desktop_1.8.0_amd64.deb`. Got this console log when starting the app via the terminal:
```
[5653:0929/085347.779061:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
08:53:48.046 › Electron's autoUpdater does not support the 'linux' platform
(node:5623) UnhandledPromiseRejectionWarning: Error: The name org.freedesktop.secrets was not provided by any .service files
(Use `parsify-desktop --trace-warnings ...` to show where the warning was created)
(node:5623) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by xxczaki** [comment]
@obstrom Thanks for letting me know. Parsify uses system's keychain to store the license file / check whether it exists. We use the [keytar](https://github.com/atom/node-keytar) library to do so. It requires `libsecret` on Linux and I suspect you may either:
- not have it installed on your OS;
- be missing one of its dependencies, for example `gnome-keyring`;

**Comment by obstrom** [comment]
Thanks, that worked! The application is now running as expected. Solved by doing `apt install gnome-keyring`.

I already had `libsecret` installed, but not `gnome-keyring`. It seems KDE uses it's own keychain called `kwallet` by default. 
@xxczaki if possible I would suggest adding `gnome-keyring` as an installation dependency on linux.

**Comment by xxczaki** [comment]
@obstrom Great, glad it worked! Good idea, I will add this package as an installation dependency in the next release.
