### ISSUE TITLE
working with square meters results in non intended behaviour

### ISSUE THREAD

**Issue by hannesw** [parsify-dev/desktop#51]
**Describe the issue**
When working with square meter unit basic operations results in incorrect result and incorrect unit. See screenshot.
**Expected result: 0,8988 m^3**

**To Reproduce (optional)**
Insert the following lines:
```
A = 0.42 m^2
U = 2.14 m
Q = A * U
```

**Screenshots (optional)**
![Image 2](https://user-images.githubusercontent.com/1560010/137748266-c85c2df8-a528-4526-958f-1c0826f6599d.png)

**Device (please complete the following information):**
 - OS: Windows 10
 - Version 1.8.0

**Additional context**
Same results when working with commas instead of points as decimal separators.
Other basic operators are alos not working.

**Comment by xxczaki** [comment]
Thanks for reporting - I'm working to fix this.

**Comment by xxczaki** [comment]
The problem will no longer occur in the next release - no ETA yet, will inform here and on Twitter, @parsifyapp :smile:

**Comment by xxczaki** [comment]
@hannesw The fix is available in [version 1.9.0](https://github.com/parsify-dev/desktop/releases/tag/v1.9.0). Extremely sorry that you had to wait that long, but I'm  a solo developer of this app.

**Comment by hannesw** [comment]
Thank you very much. It works totally fine
