### ISSUE TITLE
Deb package trashes user's /opt directory

### ISSUE THREAD

**Issue by ptrcnull** [parsify-dev/desktop#53]
**Describe the issue**
If the app is installed via package manager, it installs to `/opt/Parsify Desktop`.

**To Reproduce (optional)**
1. `dpkg -i parsify-desktop_1.8.0.deb`

**Device (please complete the following information):**
 - OS: Linux
 - Version: latest

**Comment by xxczaki** [comment]
That's the default behavior of [electron-builder](https://www.electron.build/) - which location should be used instead?
