### ISSUE TITLE
License check can be easily circumvented

### ISSUE THREAD

**Issue by ptrcnull** [parsify-dev/desktop#54]
**Describe the issue**
Users can set the key to a random value, then change `lastPing` to `Date.now()` and launch Parsify without internet.

**Comment by xxczaki** [comment]
Thanks for reporting this! I was actually thinking about such a scenario when implementing the whole offline mode. When it comes to changing the value of `lastPing` - did you modify the .json configuration file, or maybe do something totally different?

**Comment by ptrcnull** [comment]
I just opened DevTools and set a breakpoint in any place that accessed `mainStore`

**Comment by xxczaki** [comment]
Thanks for providing the details. Do you have any suggestions on how this could be reimplemented to prevent this kind of circumvention? Or maybe the only way to fix it is to simply remove the whole offline functionality?

**Comment by ptrcnull** [comment]
No matter how you try to obfuscate this, it's still security by obscurity. People will be able to open DevTools, find where the license check is and just patch it to return true every time.

With that in mind, the available options are:
- ship a code sheet to paid users and with every launch, ask them to type a code (hey, it's offline!)
- encrypt the lastPing value and store the key in the keychain with some obscure name
- guilt-trip your users like [HTTP Toolkit](https://github.com/httptoolkit/httptoolkit-ui/blob/df7494de398cb0de2fa85430ff5c63ee4f867276/src/model/account/account-store.ts#L109) and say that you won't be able to eat if people circumvent the license
- get rid of the license check altogether - you can't circumvent the checks, if there are none
- annoy the users who actually paid and can't open a calculator, because their signal is not stable enough to make a request

**Comment by xxczaki** [comment]
Right, thanks again!
