### ISSUE TITLE
Feature request: Consider saving calculated results to file, allow inline copying of multiple lines + results.

### ISSUE THREAD

**Issue by seltzered** [parsify-dev/desktop#55]
**Is your feature request related to a problem? Please describe.**
I'm trying Parsify as a long-time Calca user. Thanks for making something that runs on Linux! Two features I'd like to request is:

- The ability to copy *multiple* lines of calculations *with* the results. This helps when trying to copy multiple lines with results to share to someone (e.g. via an email)
  
- Saving the calculated results into the Parsify text file format. This way one can still recall the results of a calculation when 'previewing' the file with or without Parsify.

**Describe the solution you'd like**

- User can copy multiple lines by drag highlighting multiple from the main equation panel then moving the mouse right into the results panel.

- User can observe equations with results in the saved text file.

**Describe alternatives you've considered**

Calca actually accomplishes this by not having a results sidebar and uses a single text view but requires the user to be familiar with typing `=>` for a line to invoke results.

**Comment by xxczaki** [comment]
Hi there,

Thank you so much for the detailed feature request. I just release [version 1.9.0](https://github.com/parsify-dev/desktop/releases), which includes:
- The ability to export the calculation sheet (with results) as either a text file (.txt), or PDF.
- A `Copy Selected Lines with Results` action in the context menu when right clicking after selecting line(s) from the expressions panel.

I hope these features will satisfy your needs. Full release changelog is available [here](https://github.com/parsify-dev/desktop/releases) :smile:
