### ISSUE TITLE
It doesn't calculate anymore

### ISSUE THREAD

**Issue by xin2014** [parsify-dev/desktop#56]
It works fine yesterday, and it doesn't work today.
I have tried the following and still doesn't work
- Delete C:\Users\Sword\AppData\Roaming\Parsify Desktop\
- Uninstall app, download the latess 1.8.0 version and install
![image](https://user-images.githubusercontent.com/7124907/147522498-0b286ac4-2e12-4ade-ba27-fa0da38d95bf.png)
OS: windows 10

**Comment by xxczaki** [comment]
Hi there,

Sorry for a late reply. Could you please try and download the [latest version (1.9.0)](https://github.com/parsify-dev/desktop/releases)? I just released it and it includes a lot of bug fixes. If the issue will still be present there, take a look at the new documentation page - [troubleshooting](https://docs.parsify.app/documentation/troubleshooting).

Let me know if that helps - if not, I will do some investigation myself :smile:

**Comment by flakshack** [comment]
I'm having the same problem with the latest version (1.9.1), just downloaded today.

**Comment by xxczaki** [comment]
@flakshack @xin2014

Version 1.9.1 had an issue with calculations, that occured for some Windows (and possibly Linux) users. Thanks to the feedback I rolled a fix in v1.9.2 - could you please try it?

**Comment by flakshack** [comment]
Thanks.  It is working now.

**Comment by xxczaki** [comment]
@xin2014 Closing this for now, please let me know if you still experience this issue in the latest release, so I can reopen it.
