### ISSUE TITLE
Exception when entering certain character sequences

### ISSUE THREAD

**Issue by szabiyako** [parsify-dev/desktop#59]
**Description**
When typing ")=" or "(=" or "+=" or "*=" programm catches exception:
"Application error: a client-side exception has occurred (see the browser console for more information)."
After this exception, nothing is evaluated until the application is restarted.
Looks like syntax analyzer error.

**Screenshots**
![image](https://user-images.githubusercontent.com/39251520/150604186-808eccea-5b6c-4bd1-aa49-5436c3c93b0c.png)
![image](https://user-images.githubusercontent.com/39251520/150604368-8ddbb132-7722-4fb4-bdc2-762b3742f24d.png)
![image](https://user-images.githubusercontent.com/39251520/150604723-29dbbfc4-d536-4fe3-8f29-477c23d8b9fd.png)

**Device:**
 - OS: Windows 10 (20H2)
 - Version 1.9.2

**Comment by xxczaki** [comment]
Thank you so much for reporting this! This is an issue with the syntax highlighting - if you disable it via the Preferences page, it will no longer occur. Working on a fix right now.

**Comment by xxczaki** [comment]
Fixed in v1.9.3
