### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by nblackburn** [parsify-dev/desktop#6]
Allow the date format to be changed in the settings.

**Comment by xxczaki** [comment]
Added in `1.1.0`!

**Comment by LarsJandel** [comment]
Hm, the preferences are there, but it seems they do not have an effect..?
Expected result. [I removed the `00:00`,  see below ↓]
```
2 weeks from today  |  200621
saturday evening    |  200613 19:00
in about 2 days     |  200609
```
Also not sure about the `00:00` added to dates when not looking for a specific time.
Thanks.

![Parsify Desktop - 1 - date pref](https://user-images.githubusercontent.com/32457827/83972869-f84b9680-a8e2-11ea-8e6b-40c9c940c74a.png)
![Parsify Desktop - 2 - date](https://user-images.githubusercontent.com/32457827/83972871-f8e42d00-a8e2-11ea-8099-d521a4f2ccd6.png)

**Comment by xxczaki** [comment]
@LarsJandel I can confirm I was able to reproduce it on my Windows machine as well. It seems to work just fine on Linux though. I will look into that.

The date parser automatically adds "00:00" as the default time, when it's not been specified. I might be able to fix this relatively easily, but I will focus on the first issue for now.
