### ISSUE TITLE
Feature request: drag and drop results

### ISSUE THREAD

**Issue by kvn8888** [parsify-dev/desktop#62]
We can copy results by simply clicking on them. But if we want to re-use these results in our equations, this feature would be helpful. Clicking and dragging results back to the console is intuitive  

Also, can there be an option to have a dark title bar on windows? https://imgur.com/TYp1n59

**Comment by xxczaki** [comment]
Great suggestion, expect it to land in the next release. When it comes to the dark title bar on Windows, that's on the roadmap, although I can't guarantee that it will be available as soon as the drag and drop.

**Comment by xxczaki** [comment]
Drag-and-drop is now available in the recent release. Please note, however, that dragging and dropping the result onto the expressions pane does not yet create a reference - meaning that when you update the line with the result it won't change in the location where it was dropped.

Dark title bar on Windows is also available and it looks great IMO :smile:
