### ISSUE TITLE
History is missing on app restart

### ISSUE THREAD

**Issue by jnkb** [parsify-dev/desktop#63]
**Describe the issue**
After restarting the app, the previously entered text is no longer visible.

**To Reproduce (optional)**
1. Enter something
2. Close app
3. Open app
4. See history is empty
5. Open & Close preferences
6. History become visible

**Screenshots (optional)**
short video:
https://user-images.githubusercontent.com/26929742/158378313-91859855-8816-4cb9-9154-be3ee5823332.mp4

**Device (please complete the following information):**
 - OS: Win10
 - Version 1.9.3

**Additional context**
I have already tried a reinstallation with previously uninstalling and deleting the parsify folders in appdata\local and appdata\roaming.

**Comment by xxczaki** [comment]
This issue should no longer occur in the recent beta release.
