### ISSUE TITLE
Blinking result field

### ISSUE THREAD

**Issue by Gdenich** [parsify-dev/desktop#65]
After installing the app (Windows 11, x64), I can enter the expressions but the result field is only blinking, and does not show the result figures.
![2022-04-09_12-07-46](https://user-images.githubusercontent.com/68614536/162564987-2b5c59cd-775f-40d5-ac61-85ec709f0bcb.png)
[main.log](https://github.com/parsify-dev/desktop/files/8456616/main.log)
.

**Comment by xxczaki** [comment]
Thank you for your report. Please install the [recent beta release](https://github.com/parsify-dev/desktop/releases/latest) and try again.

**Comment by Gdenich** [comment]
Installed v2.0.0-beta.2, still the same, blinking result
![2022-04-09_23-04-23](https://user-images.githubusercontent.com/68614536/162590035-764ff0dc-1705-45bf-96bb-ece7732ce934.png)

[main.log](https://github.com/parsify-dev/desktop/files/8457679/main.log)

**Comment by xxczaki** [comment]
Try deleting the whole `%USERPROFILE%\AppData\Roaming\Parsify Desktop\` folder and then reinstalling the application.

**Comment by xxczaki** [comment]
I also added some troubleshooting enhancements when it comes to logs in the recent beta release, [v2.0.0-beta.3](https://github.com/parsify-dev/desktop/releases/latest).

**Comment by Gdenich** [comment]
Made a clean install of beta.3, cleaned %USERPROFILE%\AppData\Roaming\Parsify Desktop\ before installation. Still the same. Something wrong with my machine, as the other machine with Win11 x64 works perfectly.
[main.log](https://github.com/parsify-dev/desktop/files/8491700/main.log)

**Comment by xxczaki** [comment]
@Gdenich Can you please try and disable both of these third-party services in the preferences?

![CleanShot 2022-04-14 at 21 46 23@2x](https://user-images.githubusercontent.com/22645979/163464939-75655548-1ef9-4cc3-b084-666bf3ba9715.png)
![CleanShot 2022-04-14 at 21 46 44@2x](https://user-images.githubusercontent.com/22645979/163464949-c21ae605-c528-4b45-9c08-5b1d39ad8dd5.png)

**Comment by xxczaki** [comment]
Another thing you may try is to add `NODE_TLS_REJECT_UNAUTHORIZED=0` in the configuration field, like so:

<img width="732" alt="CleanShot 2022-04-14 at 21 53 43@2x" src="https://user-images.githubusercontent.com/22645979/163465760-891de12e-9f71-4e7c-908c-daf56bdd3ef5.png">

**Comment by Gdenich** [comment]
That's it! "Enable currency conversion" makes results blinking

**Comment by Gdenich** [comment]
"NODE_TLS_REJECT_UNAUTHORIZED=0" makes everything working with all two plugins enabled! Thank you!

**Comment by xxczaki** [comment]
Glad to hear! I'm not going to add this configuration flag as built-in yet, as I need to investigate this issue further - nevertheless, please use this flag for now as a solution :smile:
