### ISSUE TITLE
Natural logarithm (ln) and Common logarithm (lg)

### ISSUE THREAD

**Issue by Sergo1217** [parsify-dev/desktop#66]

**Comment by xxczaki** [comment]
@Sergo1217 Thank you so much for your patience; please see https://headwayapp.co/parsify-changelog/2-0-0-230230.

**Comment by Sergo1217** [comment]
That's fine, but now we need to make "log" count the binary logarithm instead of the natural logarithm
![image](https://user-images.githubusercontent.com/16447886/232248116-e549f450-f38e-452c-8f43-70478fd1ac14.png)
