### ISSUE TITLE
"Open recent" menu is always empty

### ISSUE THREAD

**Issue by manoverda** [parsify-dev/desktop#74]
**Describe the issue**
The "Open Recent" menu never shows the recent file opened, it is always empty

**To Reproduce (optional)**
1. Go to 'File'
2. Go to 'Open Recent'

**Result**
The list is always empty. Only the "Clear Recent" item is displayed.

**Device (please complete the following information):**
 - OS: Windows 10
 - Version 2.0.0-rc3

**Additional context**

**Comment by xxczaki** [comment]
@manoverda Thank you so much for your patience; please see https://headwayapp.co/parsify-changelog/2-0-0-230230.
