### ISSUE TITLE
"CTRL-R" erase the file content

### ISSUE THREAD

**Issue by manoverda** [parsify-dev/desktop#75]
**Describe the issue**
When you hit the shortkey "CTRL-R" to force recalculation, the file content is erased and saved

**To Reproduce (optional)**
1. Open a file with content
2. Hit CTRL-R to force recalculation of your file

**Result**
The file content is erased and saved. CTRL-Z doesn't allow to undo that, the file content is definitely lost.

**Screenshots (optional)**
Add screenshots to help explain your problem.

**Device (please complete the following information):**
 - OS: Windows 10
 - Version 2.0.0-rc3

**Additional context**

**Comment by manoverda** [comment]
@xxczaki 
where you able to reproduce the issue? Do you need support from me?
The CTRL-R, CTRL-Z and CTRL-S shortcuts dysfunctions on my environment are killing the app. So I would like to know if I'm the only one having this trouble, or is it a 2.0 bug? And if it is planned to have a fix on it.
Thanks & Regards,

**Comment by manoverda** [comment]
@xxczaki 
I can still offer support for this issue.
I don't know if you're able to reproduce the issue.

Regards,

**Comment by brent-hill** [comment]
Having the same issue here (Win 11).

**Comment by xxczaki** [comment]
@manoverda @brent-hill Thank you so much for your patience; please see https://headwayapp.co/parsify-changelog/2-0-0-230230.

**Comment by manoverda** [comment]
Hi @xxczaki 
Thanks so much for the fix.
Sadly, I can see what you fixed in the changelog, but the release is not available.
Neither on the application website https://parsify.app/ that stills propose to download the release v2.0.0-rc.3, neither in the application in the "Check for Updates" menu.
Do you know when this release is planned to be shared?

**Comment by manoverda** [comment]
Hi @xxczaki 
Sorry to come back, but the issue is now closed, and still no update available.
On the website, the release is still v2.0.0-rc.3 which is the same installed on my computer with the issue raised, so I still have the same issue than before.
Can you let us know when the release 2.0.0 will be published ?

Thanks & Regards,
