### ISSUE TITLE
Focus window and select all when launching/relaunching.

### ISSUE THREAD

**Issue by CZDanol** [parsify-dev/desktop#78]
**Is your feature request related to a problem? Please describe.**
I'm trying to use the app as a replacement for the default Windows calculator. I have a dedicated button on the keyboard for the calculator, I've reconfigured it to launch Parsify. I'd like to be able to straight up start writing expressions for calculations.
 However, when the key launches the application, the application does not have keyboard focus.

**Describe the solution you'd like**
Set the keyboard focus to the expression editor upon application startup. When trying to start the application  while already running, raise the application window and again set the keyboard focus to the expression editor.

**Comment by xxczaki** [comment]
@CZDanol Thank you so much for your patience; please see https://headwayapp.co/parsify-changelog/2-0-0-230230.

**Comment by CZDanol** [comment]
Thanks for taking my feedback into consideration :)

However I must report that I've downloaded the new version and the feature does not work – nothing happens at all when relaunching the application (Windows 10 x64)
