### ISSUE TITLE
Error: Unhandled Promise Rejection - sha512 checksum mismatch

### ISSUE THREAD

**Issue by LarsJandel** [parsify-dev/desktop#8]
This error just popped out of nowhere:
<p>
<details>
<summary>Unhandled Promise Rejection</summary>

<pre><code>Error: sha512 checksum mismatch, expected lpoYIgKOzWfd+yLGdtDaoiDjkFT6LuaDimXst5cAyjNOyfrlmWuOjb1xGCziygB2ISPArDdd30kcxlgT+YjQPA==, got eytX1BeQGaCqZSjpU7222lEnJ0N8kjFm1aiJvxq2cEgLrRoiaaivmKzUj+hMT/WC5pmiYRbLciUK1d5GRpeNVQ==
    at newError (C:/Users/UserName/AppData/Local/Programs/parsify-desktop/resources/app.asar/node_modules/builder-util-runtime/out/index.js:212:17)
    at DigestTransform.validate (C:/Users/UserName/AppData/Local/Programs/parsify-desktop/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:409:35)
    at DigestTransform._flush (C:/Users/UserName/AppData/Local/Programs/parsify-desktop/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:393:14)</code></pre>

</details>
</p>

**Comment by LarsJandel** [comment]
I think it is related to the auto-updater of _Parsify_, which isn't working for me: I can see sth. happening in the dedicated update folder, but just getting the error mentioned above. Running v1.0.1 and I know there is v1.0.2. Closing and starting the app didn't help, also using the button in the _about_ page. I tried to manually install the latest version, but that resulted in another error:
`Unhandled Promise Rejection
TypeError: Cannot read property 'value' of undefined
    at C:/Users/UserName/AppData/Local/Programs/parsify-desktop/resources/app.asar/app/background.js:1:4429`
and _Parsify_ launched with a white UI and using _electron_ default behaviors within the menu, e.g. going to the _electron_ website. Uninstalled and reinstalled v1.0.1, which works.
But v1.0.2 works fine on another machine, where I did a fresh install (_Parsify_ wasn't installed there previously).
[Windows 10]

**Comment by xxczaki** [comment]
I'm currently in process of rethinking the way auto-updating should function. In terms of the `value` error - it is occuring because the existing configuration doesn't contain default values for features added in the next release. This can be fixed by deleting the `config.json` file located in `%appdata%/Parsify Desktop` (on Windows).

The next release (`1.1.0`) will include configuration migrations, so such errors won't happen anymore. I want to release it later today or tomorrow.

**Comment by LarsJandel** [comment]
Thanks for the workaround!
Note, as I couldn't find the file right away, I found another _Parsify_ folder within `Roaming` I didn't see before - containing that file, so I uninstalled _Parsify_, deleted that folder and was able to manually install `v1.0.2` 🎉
`\AppData\Roaming\Parsify Desktop\`
Thanks

**Comment by xxczaki** [comment]
`1.1.0` is now out with configuration migrations. I also replaced the "silent" auto-update with a notification. This should also be useful with https://github.com/parsify-dev/desktop/issues/7, although as I said - I'm still not 100% sure about the current auto-update state.

**Comment by xxczaki** [comment]
This issue should be fixed in `1.1.2` with the new auto-update endpoint.

**Comment by LarsJandel** [comment]
Well, this error just popped again as well...
[Parsify v1.2.0 | Windows 10]
