### ISSUE TITLE
[Bug] Input cannot calculate, log says: [PARSER]: Response code 502 (Bad Gateway)

### ISSUE THREAD

**Issue by ETOgaosion** [parsify-dev/desktop#88]
**Describe the issue**

Input contexts cannot be calculated, log says: [PARSER]: Response code 502 (Bad Gateway)

**To Reproduce (optional)**
1. Enter anything
2. See error

**Screenshots (optional)**
![image](https://github.com/parsify-dev/desktop/assets/57280232/26d32805-5d2a-437c-9634-2af8101baa64)

**Device (please complete the following information):**
 - OS: Windows 11
 - Version 2.0.1

**Comment by astroboii47** [comment]
I have the same issue :\

**Comment by xxczaki** [comment]
Hi, can you try once again? I've been working on the infrastructure behind Parsify (the data source for currencies + license validation) and there may have been some downtime.

**Comment by astroboii47** [comment]
> Hi, can you try once again? I've been working on the infrastructure behind Parsify (the data source for currencies + license validation) and there may have been some downtime.

Thank you, it is working again :)

**Comment by ETOgaosion** [comment]
It's now working~
